server:
  port: 8080

spring:
  profiles:
    active: prod # Cambia a 'prod' cuando despliegues en producción

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/people-db
    username: andres
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework: INFO
    com.javeriana.peoplehexagonal: DEBUG

mapstruct:
  defaultComponentModel: spring
